# Generated by Django 6.0.2 on 2026-02-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('age', models.IntegerField(default=0, verbose_name='Возраст')),
                ('email', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Почта')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='Номер телефона')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс')),
                ('avatar', models.FileField(blank=True, upload_to='avatar', verbose_name='Аватар')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('password', models.CharField(blank=True, max_length=200, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
