# Generated by Django 6.0.2 on 2026-03-10 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс')),
                ('receive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_transfers', to='clients.client')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_transfers', to='clients.client')),
            ],
        ),
    ]
