# Generated by Django 6.0.2 on 2026-03-09 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, verbose_name='Номер карты')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_cards', to='clients.client')),
            ],
        ),
    ]
